# Generated by Django 4.2.2 on 2023-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos_app', '0002_categoria_transacao_remove_saidas_idusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.IntegerField(),
        ),
    ]
