# Generated by Django 4.2.2 on 2023-07-14 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controle_gastos_app', '0003_alter_transacao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='idusuario',
        ),
        migrations.AddField(
            model_name='transacao',
            name='iduser',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
