# Generated by Django 4.2.2 on 2023-07-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos_app', '0004_remove_transacao_idusuario_transacao_iduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
