# Generated by Django 4.2.2 on 2023-07-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_gastos_app', '0005_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.TextField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
